select d.patient_id                                                                                              PatientPK,
       s.uuid                                                                                                 as uuid,
       i.siteCode                                                                                                SiteCode,
       d.unique_patient_no                                                                                       PatientID,
       0                                                                                                      as FacilityId,
       'KenyaEMR'                                                                                                Emr,
       'Kenya HMIS III'                                                                                          Project,
       i.facilityName                                                                                            FacilityName,
       s.visit_id                                                                                                VisitId,
       s.visit_date                                                                                              VisitDate,
       s.visit_type                                                                                           as VisitType,
       s.smoke_cigarattes                                                                                     as SmokesCigarette,
       s.number_of_years_smoked                                                                               as NumberYearsSmoked,
       s.number_of_cigarette_per_day                                                                          as NumberCigarettesPerDay,
       s.other_forms_tobacco                                                                                  as OtherFormTobacco,
       s.take_alcohol                                                                                         as TakesAlcohol,
       s.hiv_status                                                                                           as HIVStatus,
       s.family_history                                                                                       as FamilyHistoryOfCa,
       s.previous_treatment                                                                                   as PreviousCaTreatment,
       s.signs_symptoms                                                                                       as SymptomsCa,
       if(s.cervical_cancer = 'Yes', 'Cervical', if(s.colorectal_cancer = 'Yes', 'Colorectal',
                                                    if(s.retinoblastoma_cancer = 'Yes', 'RetinoBlastoma',
                                                       if(s.oral_cancer = 'Yes', 'Oral',
                                                          if(s.prostate_cancer = 'Yes', 'Prostate',
                                                             if(s.breast_cancer = 'Yes', 'Breast', NULL)))))) as CancerType,
       s.fecal_occult_screening_results                                                                       as FecalOccultBloodTest,
       s.fecal_occult_screening_treatment                                                                     as TreatmentOccultBlood,
       s.colonoscopy_method_results                                                                           as Colonoscopy,
       s.colonoscopy_method_treatment                                                                         as TreatmentColonoscopy,
       s.retinoblastoma_eua_screening_results                                                                 as EUA,
       s.retinoblastoma_eua_treatment                                                                         as TreatmentEUA,
       s.digital_rectal_prostate_examination                                                                  as DRE,
       s.digital_rectal_prostate_treatment                                                                    as TreatmentDRE,
       s.prostatic_specific_antigen_results                                                                   as PSA,
       s.prostatic_specific_antigen_treatment                                                                 as TreatmentPSA,
       s.oral_cancer_visual_exam_results                                                                      as visualExamination,
       s.oral_cancer_visual_exam_treatment                                                                    as TreatmentVE,
       s.oral_cancer_cytology_results                                                                         as Cytology,
       s.oral_cancer_cytology_treatment                                                                       as TreatmentCytology,
       s.oral_cancer_imaging_results                                                                          as Imaging,
       s.oral_cancer_imaging_treatment                                                                        as TreatmentImaging,
       s.oral_cancer_biopsy_results                                                                           as Biopsy,
       s.oral_cancer_biopsy_treatment                                                                         as TreatmentBiopsy,
       s.post_treatment_complication_cause                                                                    as PostTreatmentComplicationCause,
       s.post_treatment_complication_other                                                                    as OtherPostTreatmentComplication,
       s.referred_out                                                                                         as ReferredOut,
       s.referral_reason                                                                                      as ReferralReason,
       date(s.followup_date)                                                                                  as NextAppointmentDate,
       s.screening_type                                                                                       as ScreeningType,
       s.hpv_screening_result                                                                                 as HPVScreeningResult,
       s.hpv_treatment_method                                                                                 as TreatmentHPV,
       s.via_vili_screening_result                                                                            as VIAVILIScreeningResult,
       s.via_vili_treatment_method                                                                            as VIAVILITreatment,
       s.pap_smear_screening_result                                                                           as PAPSmearScreeningResult,
       s.pap_smear_treatment_method                                                                           as TreatmentPapSmear,
       s.colposcopy_screening_result                                                                          as Colposcopy,
       s.colposcopy_treatment_method                                                                          as TreatmentColposcopy,
       s.breast_tissue_diagnosis                                                                              as IfTissueDiagnosis,
       s.breast_tissue_diagnosis_date                                                                         as DateTissueDiagnosis,
       s.reason_tissue_diagnosis_not_done                                                                     as ReasonNotDone,
       s.clinical_breast_examination_screening_result                                                         as CBE,
       s.clinical_breast_examination_treatment_method                                                         as TreatmentCBE,
       s.ultrasound_screening_result                                                                          as Ultrasound,
       s.ultrasound_treatment_method                                                                          as TreatmentUltraSound,
       breast_tissue_diagnosis                                                                                as IfTissueDiagnosis,
       breast_tissue_diagnosis_date                                                                           as DateTissueDiagnosis,
       reason_tissue_diagnosis_not_done                                                                       as ReasonNotDone,
       s.date_created                                                                                         as DateCreated,
       s.date_last_modified                                                                                   as DateModified,
       s.voided
from kenyaemr_etl.etl_patient_demographics d
         join kenyaemr_etl.etl_cervical_cancer_screening s on d.patient_id = s.patient_id
         join kenyaemr_etl.etl_default_facility_info i
group by s.visit_id;