SELECT '' AS PatientID,
       '' AS PatientPK,
       (select siteCode from kenyaemr_etl.etl_default_facility_info) as SiteCode,
       (select siteCode from kenyaemr_etl.etl_default_facility_info) as FacilityID,
       (select FacilityName from kenyaemr_etl.etl_default_facility_info) as  FacilityName,
       'Kenya EMR' AS EMR,
       'Kenya HMIS II' AS Project,
       NOW() AS VisitDate,
       '' AS AdverseEventRegimen,
       '' AS AdverseEvent,
       '' AS AdverseEventCause,
       '' AS Severity,
       '' AS AdverseEventActionTaken,
       '' AS AdverseEventClinicalOutcome,
	   NOW() AS AdverseEventStartDate,
       NOW() AS AdverseEventEndDate,
       '' AS AdverseEventIsPregnant,null as date_created,null as date_last_modified